### ISSUE TITLE
Windows won't allow colon in file address.

### ISSUE THREAD

**Issue by sccrosby** [nctoolbox/nctoolbox#101]
I'm not sure this is an issue with nctoolbox or not, however I receive the error

"The file name contains characters that are not
contained in the filesystem encoding."

when I use ncinfo,ncread,etc with a url that contains a colon, e.g. 

https://data.nodc.noaa.gov/thredds/dodsC/ndbc/cmanwx/2013/09/NDBC_VERV4_201309_D2_v00.nc

This was never an issue on my Mac. Anyone know a work around? 

Thanks!

**Comment by rsignell-usgs** [comment]
This isn't a NCTOOLBOX issue, "ncinfo" and "ncread" are native Matlab routines.

I think you are hitting the https problem with native Matlab:

> My name is Sowmya and I am writing in reference to your Technical Support Case #02462824 regarding 'ncread https opendap urls'. 
> 
> I understand that you are unable to read data from the NOAA website (starting with “https”) using the “ncread” function. I apologize for the inconvenience you may have faced.
> The functionality of the “ncread” function has been updated in MATLAB R2017a and it works fine for sources starting with “https”. Please upgrade to MATLAB R2017a to resolve this issue.
> In order to make this work in R2016a there is a workaround. However, it has not been fully qualified and tested. Please follow the steps below for the workaround:
> Execute the following commands:
>          >>edit internal.matlab.imagesci.nc/openToRead
>  
>              Please change line 1252 from:
>              if(strncmp(this.Filename,'http:',5)) 
> 
>              to:
>                if(strncmp(this.Filename,'http',4))
>  
>              >>edit netcdf.open
>              Please make the same change on line 38.
>  
> If the changes above did not fix this issue, then the “libcurl” library used by the NetCDF library included with MATLAB does not support HTTPS and you would need to find or build your own “libcurl.dll” to replace the MATLAB “libcurl.dll”.
> I will be closing this case for now. Please let me know if you have any additional questions
> 
> Please preserve the Reference ID in further correspondence on this query. This allows our systems to automatically associate your reply to the appropriate Case. 
> 
> If you have a new technical support question, please submit a new request here: 
> http://www.mathworks.com/support/servicerequests/create.html
> 
> Sincerely, 
> Sowmya Tontepu
> MathWorks Technical Support Department
