### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by mariuskist** [nctoolbox/nctoolbox#102]
I encountered the error message
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
reading data remotely from a grb2 files I accessed.

Here an example code my code:

filepath = 'http://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2008/200811/20081130/pgbh06.gdas.2008113018.grb2';

ds=ncgeodataset(filepath);

variable = ds.geovariable('Temperature_surface');

data = variable.data(1,:,:); % this line generated the error:

It turned out to be a wrong url.

Late last year the US-departments changed all protocols from http to https.

Changing the filepath to 
filepath = 'https://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2008/200811/20081130/pgbh06.gdas.2008113018.grb2';
solved the issue.

Best regards
Marius

**Comment by rsignell-usgs** [comment]
Thanks Marius
