### ISSUE TITLE
Same as issue as the following post- has it been resolved?

### ISSUE THREAD

**Issue by purpal9** [nctoolbox/nctoolbox#106]
Hello,

I have the exact same issue as this post:

**https://github.com/nctoolbox/nctoolbox/issues/61**

I would like to know where to find an older version to download, like this user, to make this work for me please. Or other suggestions.

Thank you,
Christina
![screen shot 2017-05-25 at 2 18 41 pm](https://cloud.githubusercontent.com/assets/3801722/26468862/327300d0-4155-11e7-9d05-95e8c6e23b84.png)

**Comment by rsignell-usgs** [comment]
Try this version and see if it works:
https://github.com/nctoolbox/nctoolbox/archive/1.1.1.zip

**Comment by purpal9** [comment]
I have tried that version and had success so far. Thank you!

**Comment by rsignell-usgs** [comment]
@purpal9, if this fixed your problem, can you please close the issue?

**Comment by purpal9** [comment]
Yes please close it. And perhaps inform people with similar environments to my own that they may need this package? 

Thank you very very much!!
Christina
