### ISSUE TITLE
Application of setproxy()

### ISSUE THREAD

**Issue by mariuskist** [nctoolbox/nctoolbox#107]
Hello,

I use nctoolbox to access meteorological data from National Centers for Environmental Information 
NCEI in grib2 format via OPeNDAP.
e.g. https://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2008/200811/20081101/pgbh00.gdas.2008110100.grb2

Beeing within our institute network I try to adjust the proxy settings using the function setproxy.
That is done with the following code in my Matlab startup.m file

% coded in startup.m file -------------
run('setup_nctoolbox')
setproxy('proxyadress.ourinstitute.de',port)
% as indicated proxyadress is given as a string, port is an integer
% -------------------------------------

The proxy name and port are correct according to the admins.

Unfortunately, that leads to an error:
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.writeRecord(Unknown Source)
	at sun.security.ssl.AppOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.flushRequestOutputStream(MultiThreadedHttpConnectionManager.java:1565)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	at ucar.nc2.util.net.HTTPMethod.execute(HTTPMethod.java:284)
	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:762)
	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:713)
	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:674)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)
	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

I tried the nctoolbox version 1.1.1 and 1.1.3.
Using an WLAN connection without proxy solves the problem.

Our admins tried to figure out what is wrong.
They examined the messages sent to the proxy by my tool using stuff like port mirroring and a software called wire shark.
They found out the proxy receives a message he does not understand and askes for authentication because he does not know anything else to do.
In the sent message the proxy name is included and some binary.
It is not something you would not expect to be sent to a proxy, according to the admins.

Therefore, I wanted to ask:
Is my application of setproxy() correct ?
Does setproxy affect all protocols or do I need another function for the https protocol required since start of the year ?
Has something else changed in the setproxy function or the NetCDF-Java API ?

Best regards
Marius

**Comment by hohonuuli** [comment]
Hi Marius,

All `setproxy.m` does is pass the proxy name and port number into code in underlying netcdf library. I'm not sure what it's doing with it under the hood. 

Does the proxy that you're connecting to normally require authentication? (e.g. username and password). If not, what kind of authentication is it requesting?

**Comment by mariuskist** [comment]
Hello,

No the proxy does not require authentication for normal internet access. 

According to the admin, the proxy does not understand the message sent by setproxy.m or the NetCDF API and does not know what to do, so it asks for authentication where a human would ask me to speak properly.

Could my setproxy file be out of date ?
I have tried with the nctoolbox version 1.1.1 and 1.1.3.
In a former issue [#31](https://github.com/nctoolbox/nctoolbox/issues/31) the netCDF API had changed and the setproxy file had to be adapted.
Could that be the case again ?

Best regards
Marius

**Comment by mariuskist** [comment]
Hello,

concerning this issue I contacted UniData, the developer of the netCDF java API providing the class called by setproxy.m.

They ask if it is possible to turn to a newer version of the library.
nctoolbox uses version 4.3.15.
The newest version is as far as I know version 4.6.8 (http://www.unidata.ucar.edu/software/thredds/current/netcdf-java/).

the reason is that this old version uses that they turned to a newer version of the Apache Httpclient system at some point.

I remember having read, that turning to a newer version of the netCDF-java library, lead to errors.
Can I confirm, that changing to a newer version of the API is no option for nctoolbox ?

Best regards
Marius

**Comment by rsignell-usgs** [comment]
I don't think it should be a problem.    An easy way to try it is to just take the netcdfAll jar file
ftp://ftp.unidata.ucar.edu/pub/netcdf-java/v4.6/netcdfAll-4.6.10.jar
and point to that instead of all the individual jar files. 

So comment this line:
https://github.com/nctoolbox/nctoolbox/blob/master/java/setup_nctoolbox_java.m#L2
and replace with a  `javaaddpath('netcdfAll.jar')` command.

**Comment by mariuskist** [comment]
Hi,

there was indeed a bug in netCDF-java prohibiting the setting of a proxy.

The issue was closed in the master branch of the netCDF-API version 4.6.11., the required changes are displayed in https://github.com/Unidata/thredds/pull/924.

A jar file of the corrected API can be found here:
https://artifacts.unidata.ucar.edu/content/repositories/unidata-snapshots/edu/ucar/netcdfAll/4.6.11-
SNAPSHOT/netcdfAll-4.6.11-20170925.225407-18.jar
Using it requires the file slf4j-jdk14-1.7.25.jar which can be found here: http://central.maven.org/maven2/org/slf4j/slf4j-jdk14/1.7.25/slf4j-jdk14-1.7.25.jar .
I could confirm, that netCDF-java 4.6.11 is able to access CFSR Data through our Proxy from a Java Script.

I tried to get that version working within nctoolbox version 1.1.3.
In my startup file I run the setup
"run('setup_nctoolbox')"
"setup_nctoolbox_java.m" consists of the lines:
"javaaddpath('netcdfAll-4.6.11-20170925.225407-18.jar')
javaaddpath('slf4j-jdk14-1.7.25.jar')
root = org.apache.log4j.Logger.getRootLogger();
root.addAppender(org.apache.log4j.ConsoleAppender(org.apache.log4j.PatternLayout('%d{ISO8601} [%t] %-5p %c %x - %m%n')));
root.setLevel(org.apache.log4j.Level.WARN)"


However, the class ucar.httpservices.HTTPSession() cannot be found by Matlab.

The call 
"ds=ncgeodataset(filepath);"
leads to an error in ncdataset.m:

"Error using ncdataset (line 97)
Failed to open
https://nomads.ncdc.noaa.gov/thredds/dodsC/modeldata/cmd_pgbh/2008/200811/20081101/pgbh00.gdas.2008110100.grb2

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.NoSuchFieldError: INSTANCE

    	at
        org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:52)

    	at
        org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:56)

    	at
        org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:46)
        
    	at
        org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:82)
        
    	at
        org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:95)
        
    	at
        org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:104)
        
    	at
        org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:62)
        
    	at
        org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:572)
        
    	at
        org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:174)
        
    	at
        org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
        
    	at
        org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
        
    	at
        org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:125)
        
    	at ucar.httpservices.HTTPSession.<clinit>(HTTPSession.java:412)

    	at ucar.httpservices.HTTPFactory.newSession(HTTPFactory.java:57)

    	at ucar.httpservices.HTTPMethod.<init>(HTTPMethod.java:220)

    	at ucar.httpservices.HTTPMethod.<init>(HTTPMethod.java:194)

    	at ucar.httpservices.HTTPFactory.Get(HTTPFactory.java:127)

    	at ucar.nc2.dataset.NetcdfDataset.checkIfDods(NetcdfDataset.java:910)

    	at ucar.nc2.dataset.NetcdfDataset.disambiguateHttp(NetcdfDataset.java:827)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:706)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:427)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:410)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:395)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:382)"


Importing the class also throws an error:
"import ucar.httpservices.HTTPSession;"
Error using import
Import argument 'ucar.httpservices.HTTPSession' cannot be found or cannot be imported."

If I try to use the class directly, Matlab tells the variable is undefined.
"ucar.httpservices.HTTPSession.setGlobalProxy('http://ourproxy.com:portnumber')
Undefined variable "ucar" or class "ucar.httpservices.HTTPSession"."

The class file exists in the loaded 'netcdfAll-4.6.11-20170925.225407-18.jar'.
And the class method setGlobalProxy() works when used in a Java Program.


At http://undocumentedmatlab.com/blog/java-class-access-pitfalls I found some possible reasons for such behaviour. 
But none of them seems to be the case.
- I am confident that no mistyping is the reason. I copied the commands from the working Java Script.
- The error occurs with Matlab 2015b (Java version 1.7), 2016b (Java version 1.7), and 2017b (Java version 1.8).
  The used class works in the Java Program with Java 1.8.
- It seems not to be a dependency issue. 
  I imported all of the libraries listed in the header of HTTPSession.java into Matlab, without any warning that a library were not known.
  The libraries are listed in the source code of HTTPSession.java at:
  https://github.com/Unidata/thredds/blob/master/httpservices/src/main/java/ucar/httpservices/HTTPSession.java

- MatLab cannot load non-public classes: HTTPSession is a public class.

- MatLab cannot load static classes with non-public constructors: All constructors of HTTPSession() are protected.
  But as well are all constructors of the class "ucar.nc2.dataset.NetcdfDataset" which can be imported with no problem.

  
  
The undefined variable or class error also occurs when calling "import ucar.httpservices.HTTPMethodStream".

"import ucar.httpservices.*" 
does not lead to an error but a subsequent call
HttpSession.setGlobalProxy('https://ourproxy.com:portnumber')
does give the unknown variable error.



Has someone an idea what could be the reason for this for a solution ?

Or is it possible to implement the "set proxy" changes in https://github.com/Unidata/thredds/pull/924 (5 lines of code) within the netCDF-java version used by nctoolbox ?

Thanks a lot and best regards
Marius

**Comment by hohonuuli** [comment]
@mariuskist Hi Marius, Matlab and the more recent NetCDF-java libraries use conflicting versions of [HTTPClient](https://hc.apache.org/httpclient-3.x/)/[HTTPComponent](https://hc.apache.org/httpcomponents-client-ga/). It's been a __huge__ headache for me and prevents nctoolbox from using the more recent NetCDF-java versions. I checked the latest version of Matlab (R2017b) and they _still_ use the very, very outdated HTTPClient (i.e. `/Applications/MATLAB_R2017b.app/java/jarext/axis2/commons-httpclient.jar `).

I'm not sure how to work around this. Matlab uses a framework called [axis2](https://axis.apache.org/axis2/java/core/index.html) to enable SOAP webservices. Unfortunately, Even the most recent versions of axis2 use the old httpclient libraries. So even if Matlab uses the latest and greatest version of Axis2, we're still stuck with this problem.

**Comment by mariuskist** [comment]
I see. 

Do you by any chance have the source code of the netcdf-4.3.15.jar file used by nctoolbox.

Perhaps I could introduce the missing proxy code and compile it.

**Comment by mariuskist** [comment]
Hi,

As update: I found source code of netCDF Java version 4.3.15 at 
https://github.com/Unidata/thredds/releases?after=v4.3.17

But the HTTPSession.java file has changed a lot. 
I think I cannot implement the Bugfix for Proxy handling from version 4.6.11 in that source code.

I will try some more.

Best regards
Marius

**Comment by mariuskist** [comment]
Hi,

another update: 
I tried to use netCDF Java version 4.3.15 from a Java program (without nctoolbox) and verified its inability to pass our proxy.
The bug preventing connention through proxy is, therefore, not on nctoolbox side.

Unfortunately, UniData won't help fixing this.
They recommend upgrading to a newer version of netCDF java.

About such an Upgrade: 
A Ticket at MathWorks confirmed that they are not planning to change the MatLab HTTPClient version in near future. The conflict between their HTTPClienet and the netCDF client might remain some time.

MathWorks shared the following ideas for a workaround:

1. Backup and replace the version of HTTPClient library in MathWorks with a newer one. I did not try that fearing to brake some other Matlab functionality. I am not the only one using that Matlab installation.

2. [Solution of a similar issue with conflicting HTTPClient libraries](http://rockthecode.io/blog/leveraging-the-java-ecosystem-in-matlab/)  between Matlab and an external Java library; 

The second workaround might be a way to enable nctoolbox to use the newest netCDF java version.
As I understand, it includes to write a Java Class, which serves as Interface/seperation between the Java library (netCDF in our case) and the Matlab installation.
This class itself is loaded using the Matlab classloader. It then initializes the java.net.URLClassLoader with URLs to all JAR files needed by the java library.
In that form, the Java library and Matlab both can use "their own" dependent libraries.

As this is no longer a nctoolbox issue I close the issue.
Please let me know if nctoolbox upgrades to a newer netCDF version.

Best regards
Marius

**Comment by hohonuuli** [comment]
@mariuskist Thanks for doing the leg work and dealing with Mathworks. I'm pretty sure Matlab is just using the old HTTPClient libraries to make SOAP web service calls. I don't think anyone is really using SOAP anymore. I'll try disabling them when I get a free moment this week, upgrade to HTTPComponents and see what works and what doesn't.
