### ISSUE TITLE
compiled but error:  Undefined variable "ucar" or class "ucar.nc2.dataset.NetcdfDataset.openDataset".

### ISSUE THREAD

**Issue by phigzen** [nctoolbox/nctoolbox#109]
thanks for your toolbox , i successed in reading grib2 files in my coed. But after i had compiled it using Application Compiler, it occurrs error: Undefined variable "ucar" or class   "ucar.nc2.dataset.NetcdfDataset.openDataset".  NCTOOLBOX:ncdataset. But it also print "NCTOOLBOX added to Matlab path". So why the error occurrs and how to solve it?

**Comment by hohonuuli** [comment]
I've never used the [Application Compiler](https://www.mathworks.com/products/compiler.html). Whatever it did, it looks like it forgot to include the various java jar files in `nctoolbox\java`. You'll have to do some sleuthing to see how (or if) the Application Compiler includes Java resources, like jar files.

**Comment by phigzen** [comment]
You're right. It is executed successfully after i have include the jar files!

**Comment by hohonuuli** [comment]
Great! Thanks for letting me know.
