### ISSUE TITLE
Problem extracting content of files

### ISSUE THREAD

**Issue by marcelo-hg** [nctoolbox/nctoolbox#112]
Hi,

I'm new to nctoolbox and I'm having trouble extracting the content from files.
I think I succesessfully downloaded and instaled the toolbox since I'm able to open the files, but I can't get the content of variables. 
My MathLab version is R2015a, my Java version is 1.7.0_60-b19. 
Link to the file: http://nomads.ncep.noaa.gov/pub/data/nccf/com/wave/prod/multi_1.20180110/.

Here is the error:

>> nco=ncgeodataset('multi_1.at_10m.t00z.f000.grib2')

nco = 

  ncgeodataset with properties:

       netcdf: [1x1 ucar.nc2.dataset.NetcdfDataset]
    variables: {17x1 cell}

>> nco.variables

ans = 

    'Wind_direction_from_which_blowing_surface'
    'Wind_speed_surface'
    'u-component_of_wind_surface'
    'v-component_of_wind_surface'
    'Significant_height_of_combined_wind_waves_and_swell_surface'
    'Direction_of_wind_waves_surface'
    'Significant_height_of_wind_waves_surface'
    'Mean_period_of_wind_waves_surface'
    'Direction_of_swell_waves_ordered_sequence_of_data'
    'Significant_height_of_swell_waves_ordered_sequence_of_data'
    'Mean_period_of_swell_waves_ordered_sequence_of_data'
    'Primary_wave_direction_surface'
    'Primary_wave_mean_period_surface'
    'lat'
    'lon'
    'ordered_sequence_of_data'
    'time'
>> t=nco{'time'}(:);
Error using horzcat
The following error occurred converting from char to ncgeodataset:
Error using ncdataset (line 77)
Failed to open Failed to open

Error in ncdataset (line 75)
                ex = MException('NCDATASET:ncdataset', ['Failed to open ' url]);

Error in ncgeodataset/geovariable (line 409)
                    ncd = ncdataset(obj);

Error in ncgeodataset/subsref (line 654)
                    v = obj.geovariable(s(1).subs);

I successfully tested the downloaded files with the wgrib2 apliccation.

The toolbox only works with 1.6 version of Java?

Thank's in advance.
Marcelo

**Comment by hohonuuli** [comment]
I tried your code, but was not able to duplicate your error:

```
>> ver
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.3.0.713579 (R2017b)
MATLAB License Number: xxxxxx
Operating System: Mac OS X  Version: 10.13.2 Build: 17C88 
Java Version: Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.3         (R2017b)
Statistics and Machine Learning Toolbox               Version 11.2        (R2017b)
>> n = ncgeodataset('/Users/brian/Downloads/multi_1.ak_10m.t00z.f000.grib2')

n = 

  ncgeodataset with properties:

     location: '/Users/brian/Downloads/multi_1.ak_10m.t00z.f000.grib2'
       netcdf: [1×1 ucar.nc2.dataset.NetcdfDataset]
    variables: {17×1 cell}

>> t = n{'time'}(:)

t =

  int32

   0

>> t = n.data('time')

t =

  int32

   0
```

> The toolbox only works with 1.6 version of Java?

It should work with any version of Java >= 1.6. 

__NOTE__: I'm working with the HEAD from the git repository. Do you know which version of nctoolbox you're using?

**Comment by marcelo-hg** [comment]
Hi hohonuuli, 

The problem was an older version of the nctoolbox installed in my pc. 

Thank you for the attention.
