### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by msmall318** [nctoolbox/nctoolbox#113]
Hi,

I'm looking to cite this toolbox for a thesis.  Do you have a specified format you would prefer?

Thanks

-Matt

**Comment by hohonuuli** [comment]
I've never published a software paper about the toolbox. So I think the following is the accepted citation.

```
B. Schlining, R. Signell, nctoolbox (2009), Github repository, https://github.com/nctoolbox/nctoolbox
```

**Comment by hohonuuli** [comment]
p.s. Thanks for citing the toolbox!

**Comment by msmall318** [comment]
No problem. Thanks for the prompt response!

**Comment by hohonuuli** [comment]
Whoops ... Also add A. Crosby as the third author

**Comment by msmall318** [comment]
got it

**Comment by hohonuuli** [comment]
So just to summarize for anyone else who's looking for the citation:

```
B. Schlining, R. Signell, A. Crosby, nctoolbox (2009), Github repository, 
    https://github.com/nctoolbox/nctoolbox
```

**Comment by drf5n** [comment]
Maybe add it to https://github.com/nctoolbox/nctoolbox ?

**Comment by hohonuuli** [comment]
Added citation to bottom of README.md
