### ISSUE TITLE
Java out of space

### ISSUE THREAD

**Issue by deryadilmen** [nctoolbox/nctoolbox#124]
Hello,

It is not directly related with nctoolbox but I get this error when I run **ds.data** 

_Java exception occurred:
java.lang.OutOfMemoryError: Java heap space_

How can I increase my Java memory?

Thank you

**Comment by hohonuuli** [comment]
It looks like you found you're own solution. In case someone else reads this issue. Here's the solution: <https://www.mathworks.com/help/matlab/matlab_external/java-heap-memory-preferences.html>

**Comment by deryadilmen** [comment]
Thank you for the great and fast solution, I had to reinstall Java and increase it's size with -Xmx comment.
