### ISSUE TITLE
nj_tseries not working when attempting to read .grb2 NOAA WW3 files

### ISSUE THREAD

**Issue by felipemrno** [nctoolbox/nctoolbox#125]
Hi, I need to work with wave data from NOAA's WW3, so I wrote the following code. The thing is I need data for only one pair of lat/lon coordinates. Reading on the internet, I found a way to do so with nj_tseries. My code works fine to until it reaches de nj_tseries line. I previously increased the Java Heap memory because the upper part of the code wasn't working. I'd kindly appreciate any help on this, or suggestions on how to extract the data for a specific pair of coordinates.

Matlab R2020a
Nctoolbox 1.1.0
Java version: 'Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'

%%%%%%%%%%%
clc
clear all

addpath(genpath('C:\Nctoolbox'));     
setup_nctoolbox

fname = 'multi_1.glo_30m.hs.201610.grb2';
nc    =  ncgeodataset('multi_1.glo_30m.hs.201610.grb2');
Hs    = nc.geovariable('Significant_height_of_combined_wind_waves_and_swell_surface');
lon   = nc.data('lon');
lat   = nc.data('lat');
YYYY  = str2num(fname(20:23));
MO    = str2num(fname(24:25));
time  = double(nc.data('time'))/24 + datenum(YYYY,MO,1,0,0,0);

param='Significant_height_of_combined_wind_waves_and_swell_surface';
lat0=-33.5;
lon0=72;
 
nj_tseries(nc,param,lon0,lat0)

%%%%%%%%%%%%%%%

This is the error I'm getting:

Error using ncdataset/readdata (line 500)
Java exception occurred:
java.io.FileNotFoundException: data file not found = C:/Users/Felipe/Documents/MATLAB/multi_1.glo_30m.hs.201610.grb2

	at ucar.nc2.grib.GribCollection.getDataRaf(GribCollection.java:387)

	at ucar.nc2.grib.grib2.Grib2Iosp$DataReader.read(Grib2Iosp.java:973)

	at ucar.nc2.grib.grib2.Grib2Iosp.readDataFromCollection(Grib2Iosp.java:912)

	at ucar.nc2.grib.grib2.Grib2Iosp.readData(Grib2Iosp.java:720)

	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1957)

	at ucar.nc2.Variable.reallyRead(Variable.java:879)

	at ucar.nc2.Variable._read(Variable.java:865)

	at ucar.nc2.Variable.read(Variable.java:677)

	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:553)

	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:533)

	at ucar.nc2.Variable.read(Variable.java:677)

	at ucar.nc2.Variable.read(Variable.java:651)

Error in ncdataset/data (line 165)
                    d = obj.readdata(variable, first, last, stride);

Error in ncgeodataset/subsref (line 386)
                            B = builtin('subsref',obj,g);

Error in ncvariable/somedata (line 353)
                data = obj.dataset.data(name, first, last, stride);

Error in ncvariable/data (line 174)
                d = somedata(obj, 1, first, last, stride);

Error in ncgeovariable/subsref (line 1076)
                                        sref = obj.data(first, last, stride);

Error in ncgeodataset/subsref (line 416)
                        B = v.data(s(2).subs{:});

Error in nj_tseries (line 105)
          u(:,k)=squeeze(nc{var}(itime,jj,ii));

Error in read_grb2_Hsig_WW3 (line 28)
nj_tseries(nc,'Significant_height_of_combined_wind_waves_and_swell_surface',72,-33.5)

**Comment by hohonuuli** [comment]
Can you provide a link to the dataset?

**Comment by rsignell-usgs** [comment]
Since using `fname` apparently worked, maybe try:
```
fname = 'multi_1.glo_30m.hs.201610.grb2';
param='Significant_height_of_combined_wind_waves_and_swell_surface';
lat0=-33.5;
lon0=72;

nj_tseries(nc,param,lon0,lat0)
```

**Comment by felipemrno** [comment]
> Can you provide a link to the dataset?

Sure:

ftp://polar.ncep.noaa.gov/pub/history/waves/multi_1/201610/gribs/

Any 'multi_1.glo_30m.' with hs, dp & tp is what I'm trying to open.

**Comment by felipemrno** [comment]
> Since using `fname` apparently worked, maybe try:
> 
> ```
> fname = 'multi_1.glo_30m.hs.201610.grb2';
> param='Significant_height_of_combined_wind_waves_and_swell_surface';
> lat0=-33.5;
> lon0=72;
> 
> nj_tseries(fname,param,lon0,lat0)
> ```

It makes no difference, still stuck at the same line.

**Comment by hohonuuli** [comment]
I'm running a test using nctoolbox 1.1.0 and:

```
MATLAB Version: 9.8.0.1359463 (R2020a) Update 1
MATLAB License Number: 177731
Operating System: Mac OS X  Version: 10.15.4 Build: 19E287 
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
```

I ran the following:

```matlab
nc = ncgeodataset('/Users/brian/Downloads/multi_1.glo_30m.hs.201610.grb2');
fname = 'multi_1.glo_30m.hs.201610.grb2';
lat = nc.data('lat');
YYYY = str2num(fname(20:23));
MO = str2num(fname(24:25));
time = double(nc.data('time'))/24 + datenum(YYYY,MO,1,0,0,0);
param='Significant_height_of_combined_wind_waves_and_swell_surface';
lat0=-33.5;
lon0=72;
nj_tseries(nc,param,lon0,lat0)
```

When running `nj_tseries(nc,param,lon0,lat0)` it returns the following:

```
>> nj_tseries(nc,param,lon0,lat0)
extracting point 1:lon=72.000000,lat=-33.500000

ans = 

  struct with fields:

      ii: 145
      jj: 223
    vals: [249×1 double]
     lon: 72
     lat: -33.5000
    time: [249×1 double]
```

**Comment by hohonuuli** [comment]
@felipemrno Is your data file actually located at `C:/Users/Felipe/Documents/MATLAB/multi_1.glo_30m.hs.201610.grb2`?

**Comment by felipemrno** [comment]
> @felipemrno Is your data file actually located at `C:/Users/Felipe/Documents/MATLAB/multi_1.glo_30m.hs.201610.grb2`?

No, it's in the same directory i'm running the script. That caught my attention and I don't understand how to fix it.

**Comment by hohonuuli** [comment]
Try using the full path when you open the dataset and see if that addresses the issue:

```matlab
% nc = ncgeodataset('multi_1.glo_30m.hs.201610.grb2');
nc = ncgeodataset('C:/Users/Felipe/path/to/file/multi_1.glo_30m.hs.201610.grb2');
```

**Comment by felipemrno** [comment]
> Try using the full path when you open the dataset and see if that addresses the issue:
> 
> ```matlab
> % nc = ncgeodataset('multi_1.glo_30m.hs.201610.grb2');
> nc = ncgeodataset('C:/Users/Felipe/path/to/file/multi_1.glo_30m.hs.201610.grb2');
> ```

This worked perfectly, thank you so much for your time and help!
