### ISSUE TITLE
A Chinese version of nctoolbox wiki

### ISSUE THREAD

**Issue by tfoterye** [nctoolbox/nctoolbox#127]
[Nctoolbox 使用说明中文版.pdf](https://github.com/nctoolbox/nctoolbox/files/4713933/Nctoolbox.pdf)
I'm using nctoolbox and I'm exciting about finding such a terrific toolbox for reading meteorology data. However as I'm a Chinese, some of my colleagues or classmates cannot understand the wiki and instruction exactly. So I translate the wiki and instruction (mostly from https://github.com/nctoolbox/nctoolbox/wiki  and http://nctoolbox.github.io/nctoolbox/ ) into Chinese. I want the permit from main contributors (@hohonuuli  , @rsignell-usgs , @drf5n , @acrosby , @ocefpaf ) and I promise for using it under your authorization.
I hope it may help other people when using this toolbox.

**Comment by hohonuuli** [comment]
@tfoterye: Thanks for contributing the docs! That's fantastic and very much appreciated. I've added your PDF to the master branch and linked it at the top of the readme so your colleagues can find it easily.
