### ISSUE TITLE
Error reading nc files

### ISSUE THREAD

**Issue by mfrab** [nctoolbox/nctoolbox#130]
Hello,
I am trying to read .nc files using NCTOOLBOX - 20130305, but there is an error. 
[main] ERROR ucar.nc2.iosp.hdf5.H5header  - bad version 72 at filePos 342929

any suggestion will be appreciate!
Thanks in advance

My system Info are follows;
OS : window 10 64bit
[dt_med_twosat_phy_l4_19930102_vDT2018.zip](https://github.com/nctoolbox/nctoolbox/files/5873414/dt_med_twosat_phy_l4_19930102_vDT2018.zip)

JAVA : Java 1.7.0
Matlab : R2017a
nctoolbox : 20130305
INPUT FILE dt_med_twosat_phy_l4_19930102_vDT2018.nc
I can successfully read grib files but it does not work with .nc files.

**Comment by hohonuuli** [comment]
> [main] ERROR ucar.nc2.iosp.hdf5.H5header - bad version 72 at filePos 342929

Are you running into any actual problems using that file? Other than displaying a message about a bad header the file seems to work OK. Am I missing something? I ran a quick test with this code:

```matlab
nc = cfdataset('dt_med_twosat_phy_l4_19930102_vDT2018.nc');
sla = nc.struct('sla');
lon = double(sla.longitude);
lat = double(sla.latitude);
z = squeeze(double(sla.sla));
surf(lat, lon, z');
view(2);
shading('interp');
xlabel('longitude');
ylabel('latitude');
axis('equal');
colorbar;
title('Sea level anomaly');
```

**Comment by mfrab** [comment]
Thank you very much. It's the first time that i'm using nc files and this dataset and I'm writing a code line by line...
I thought the error message did not allow to go on. 
Sorry for the inconvenience, you have been very kind.
