### ISSUE TITLE
issue with reading wind wave spectrum

### ISSUE THREAD

**Issue by RMarsooli** [nctoolbox/nctoolbox#132]
Hi - We're using the toolbox to read direction-frequency wind wave spectrum from ECMWF ERA5 reanalysis. The wave spectrum has five dimensions: (time, lat, lon, frequency, direction). However, the toolbox only detects three dimensions (time, lat, lon), and misses frequency and direction. The output wave spectrum has three dimensions instead of five. Any help is greatly appreciated.

**Comment by hohonuuli** [comment]
@RMarsooli Can you provide a sample file of your data to test against?

**Comment by RMarsooli** [comment]
> @RMarsooli Can you provide a sample file of your data to test against?

Please see the sample: https://drive.google.com/file/d/1xIkentkO6fdXiU2lkj2uYEa4smoBhVhb/view?usp=sharing

**Comment by hohonuuli** [comment]
@RMarsooli The CDL for your data file as read by [NetCDF-Java](https://www.unidata.ucar.edu/software/netcdf-java/) is below.

```
>>  n = ncdataset('/Users/brian/Downloads/WaveSpectra2.grib')
>>  n.netcdf

ans = 

netcdf /Users/brian/Downloads/WaveSpectra2.grib {
  dimensions:
    lon = 1000;
    lat = 501;
    time = 3;
  variables:
    float 2D_wave_spectra_single_msl(time=3, lat=501, lon=1000);
      :long_name = "2D wave spectra single @ Mean sea level";
      :units = "m2.s.radian-1";
      :missing_value = NaNf; // float
      :Grib_Variable_Id = "VAR_98-0-140-251_L102";
      :Grib1_Center = 98; // int
      :Grib1_Subcenter = 0; // int
      :Grib1_TableVersion = 140; // int
      :Grib1_Parameter = 251; // int
      :Grib1_Parameter_Name = "2DFD";
      :Grib1_Level_Type = 102; // int
      :Grib1_Level_Desc = "Mean sea level";

    float lat(lat=501);
      :units = "degrees_north";
      :_CoordinateAxisType = "Lat";

    float lon(lon=1000);
      :units = "degrees_east";
      :_CoordinateAxisType = "Lon";

    int time(time=3);
      :units = "Hour since 2020-01-01T00:00:00Z";
      :standard_name = "time";
      :long_name = "product valid at RT + P1";
      :_CoordinateAxisType = "Time";

  // global attributes:
  :Originating_or_generating_Center = "European Centre for Medium Range Weather Forecasts (ECMWF) (RSMC)";
  :Originating_or_generating_Subcenter = "0";
  :Conventions = "CF-1.6";
  :history = "Read using CDM IOSP Grib1Collection";
  :featureType = "GRID";
  :file_format = "GRIB-1";
  :_CoordSysBuilder = "ucar.nc2.dataset.conv.CF1Convention";
}
```

Using [cfgrib](https://github.com/ecmwf/cfgrib) in python I can see dimensions and vars not shown by Netcdf-Java:

```
import cfgrib
ds = cfgrib.open_file("WaveSpectra2.grib")
>>> ds.dimensions.keys()
dict_keys(['time', 'directionNumber', 'frequencyNumber', 'values'])
>>> ds.variables.keys()
dict_keys(['number', 'time', 'step', 'meanSea', 'directionNumber', 'frequencyNumber', 'latitude', 'longitude', 'valid_time', 'd2fd'])
>>>
```

So. This is likely a bug in the grib library that Netcdf-Java is using. The bug may even be patched in more recent versions. Unfortunately, there's a conflict in Java libraries built in to Matlab and recent versions of NetCDF java that prevents nctoolbox from being upgraded. 🤷
