### ISSUE TITLE
Failed to setup the Java classpath

### ISSUE THREAD

**Issue by Phuongtran75** [nctoolbox/nctoolbox#138]
Hi,
I'm new to the NCF format. I tried to install nctoolbox to Matlab 2023a. During the installation process, I got an error with the Java installation.
I followed suggestions online to comment the 6 row in the setup_nctoolbox_java.m file, and the package has not been installed successfully.

>> setup_nctoolbox
Error using setup_nctoolbox
Failed to setup the Java classpath

>> setup_nctoolbox_java
No constructor 'org.apache.log4j.ConsoleAppender' with matching signature found.
Error in setup_nctoolbox_java (line 6)
root.addAppender(org.apache.log4j.ConsoleAppender(org.apache.log4j.PatternLayout('%d{ISO8601} [%t] %-5p %c %x - %m%n')));

Can you tell me how to fix this solution?

Thanks!
Phuong

**Comment by hohonuuli** [comment]
The fix is to comment out line 6 in `setup_nctoolbox_java.m`.
