### ISSUE TITLE
Reading GRIB1 file w/ ncgeodataset is returning Java errors (Java is already up-to-date)

### ISSUE THREAD

**Issue by ajoros** [nctoolbox/nctoolbox#28]
Hey guys,

First post here. 

I am attempting to load a GRIB1 file using ncgeodataset and it is returning Java errors. You can see the code below. I have MATLAB 2013a and Java is up to date.
You can download the GRIB1 file used in this test here:  https://dl.dropboxusercontent.com/u/561373/ST4.2002012912.24h
I am using the latest stable version of nctoolbox. 

``` matlab
>> version
ans =
8.1.0.604 (R2013a)

>> version('-java')
ans =
Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode


%% LINE OF CODE WITH ERROR BELOW:
>> g=ncgeodataset('ST4.2002012912.24h')
Error using ncdataset (line 97)
Failed to open ST4.2002012912.24h

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.RuntimeException: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

        at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1535)

        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

        at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

        at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

        at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

        at ucar.nc2.grib.grib1.Grib1IndexProto$Grib1Index.access$3000(Grib1IndexProto.java:1178)

        at
        ucar.nc2.grib.grib1.Grib1IndexProto$Grib1Index$Builder.maybeForceBuilderInitialization(Grib1IndexProto.java:1459)

        at ucar.nc2.grib.grib1.Grib1IndexProto$Grib1Index$Builder.<init>(Grib1IndexProto.java:1451)

        at ucar.nc2.grib.grib1.Grib1IndexProto$Grib1Index$Builder.create(Grib1IndexProto.java:1465)

        at ucar.nc2.grib.grib1.Grib1IndexProto$Grib1Index$Builder.access$2800(Grib1IndexProto.java:1436)

        at ucar.nc2.grib.grib1.Grib1IndexProto$Grib1Index.newBuilder(Grib1IndexProto.java:1423)

        at ucar.nc2.grib.grib1.Grib1Index.makeIndex(Grib1Index.java:210)

        at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:112)

        at ucar.nc2.grib.grib1.Grib1Iosp.open(Grib1Iosp.java:135)

        at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

        ... 7 more
```

Thanks for any and all help! 

aj

**Comment by jbadag** [comment]
Hello all,

I have a problem. I want to read gfs 0.5 degree output, but i can't read.
I download the files ouput at specific time 
http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2016010606/gfs.t06z.pgrb2.0p25.f003
http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2016010606/gfs.t06z.pgrb2.0p25.f003.idx.

I followed the instructions: 

1. Create a file javaclasspath.txt either in your preferences folder or in your MATLAB startup folder. (Run prefdir in MATLAB to locate your preferences folder)
2. Add a line that contains the path of nctoolbox's protocol buffer jar. It will look something like: /Users/brian/workspace/nctoolbox/javaprotobuf-java-2.4.1.jar. Your path will be different but you get the idea.
3. Save javaclasspath.txt and restart MATLAB.

but not run. I get the following error message:


>> setup_nctoolbox
NCTOOLBOX added to Matlab path
>> nc=ncgeodataset('gfs.t06z.pgrb2.0p50.f240')
2016-01-06 11:41:56,486 [main] WARN  ucar.nc2.grib.grib2.Grib2Index  - Grib2Index bad size = -1 for gfs.t06z.pgrb2.0p50.f240 index = gfs.t06z.pgrb2.0p50.f240.gbx9

Error using ncdataset (line 97)
Failed to open gfs.t06z.pgrb2.0p50.f240

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.RuntimeException: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1535)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.access$5400(Grib2IndexProto.java:2635)

    	at
        ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.maybeForceBuilderInitialization(Grib2IndexProto.java:2914)
        
    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.<init>(Grib2IndexProto.java:2906)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.create(Grib2IndexProto.java:2920)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.access$5200(Grib2IndexProto.java:2891)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.newBuilder(Grib2IndexProto.java:2878)

    	at ucar.nc2.grib.grib2.Grib2Index.makeIndex(Grib2Index.java:231)

    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:112)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	... 7 more


can you help me?

**Comment by jbadag** [comment]
Hello all,

I want to read gfs outputs in matlab, but i can't read the file. 
I download the files at specific time: 
http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2016010606/gfs.t06z.pgrb2.0p50.f003 
http://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.2016010606/gfs.t06z.pgrb2.0p50.f003.idx

and  I follow the instructions: 
1. Create a file javaclasspath.txt either in your preferences folder or in your MATLAB startup folder. (Run prefdir in MATLAB to locate your preferences folder)
2. Add a line that contains the path of nctoolbox's protocol buffer jar. It will look something like: /Users/brian/workspace/nctoolbox/javaprotobuf-java-2.4.1.jar. Your path will be different but you get the idea.
3. Save javaclasspath.txt and restart MATLAB.

but matlab  displays an error message:

>> setup_nctoolbox
NCTOOLBOX added to Matlab path
>> nc=ncgeodataset('gfs.t06z.pgrb2.0p50.f003 ')
2016-01-06 11:41:56,486 [main] WARN  ucar.nc2.grib.grib2.Grib2Index  - Grib2Index bad size = -1 for gfs.t06z.pgrb2.0p50.f240 index = gfs.t06z.pgrb2.0p50.f240.gbx9

Error using ncdataset (line 97)
Failed to open gfs.t06z.pgrb2.0p50.f240

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.RuntimeException: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1535)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.access$5400(Grib2IndexProto.java:2635)

    	at
        ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.maybeForceBuilderInitialization(Grib2IndexProto.java:2914)
        
    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.<init>(Grib2IndexProto.java:2906)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.create(Grib2IndexProto.java:2920)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.access$5200(Grib2IndexProto.java:2891)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.newBuilder(Grib2IndexProto.java:2878)

    	at ucar.nc2.grib.grib2.Grib2Index.makeIndex(Grib2Index.java:231)

    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:112)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	... 7 more


can you help me please?

**Comment by hohonuuli** [comment]
@jbadag Can you run `ver` in Matlab and post it? Also, which version of nctoolbox are you running?

**Comment by jbadag** [comment]
@hohonuuli 
I run and matlab 
 nc=ncgeodataset('gfs.t06z.pgrb2.0p50.f240')

and display an error message: 


Error using ncdataset (line 97)
Failed to open gfs.t06z.pgrb2.0p50.f240

Error in cfdataset (line 59)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 74)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 81)
    Java exception occurred:
    java.lang.RuntimeException: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1535)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: java.lang.NoSuchFieldError: alwaysUseFieldBuilders

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.access$5400(Grib2IndexProto.java:2635)

    	at
        ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.maybeForceBuilderInitialization(Grib2IndexProto.java:2914)
        
    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.<init>(Grib2IndexProto.java:2906)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.create(Grib2IndexProto.java:2920)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index$Builder.access$5200(Grib2IndexProto.java:2891)

    	at ucar.nc2.grib.grib2.Grib2IndexProto$Grib2Index.newBuilder(Grib2IndexProto.java:2878)

    	at ucar.nc2.grib.grib2.Grib2Index.makeIndex(Grib2Index.java:231)

    	at ucar.nc2.grib.GribIndex.makeGribCollectionFromSingleFile(GribIndex.java:112)

    	at ucar.nc2.grib.grib2.Grib2Iosp.open(Grib2Iosp.java:310)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	... 7 more

I download the folder nctoolbox-master in https://github.com/nctoolbox/nctoolbox

thanks!

**Comment by hohonuuli** [comment]
@jbadag Thanks for the steps, but it's very helpful for debugging to know which version of Matlab you are running. Please run the following command in Matlab:

```matlab
ver
```
and paste the output into this thread. Thanks

**Comment by jbadag** [comment]
-------------------------------------------------------------------------------------------------------
MATLAB Version: 8.1.0.604 (R2013a)
MATLAB License Number: 724504
Operating System: Microsoft Windows 7 Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
-------------------------------------------------------------------------------------------------------
MATLAB                                                Version 8.1        (R2013a)
Simulink                                              Version 8.1        (R2013a)
Aerospace Blockset                                    Version 3.11       (R2013a)
Aerospace Toolbox                                     Version 2.11       (R2013a)
Bioinformatics Toolbox                                Version 4.3        (R2013a)
Communications System Toolbox                         Version 5.4        (R2013a)
Computer Vision System Toolbox                        Version 5.2        (R2013a)
Control System Toolbox                                Version 9.5        (R2013a)
Curve Fitting Toolbox                                 Version 3.3.1      (R2013a)
DO Qualification Kit                                  Version 2.1        (R2013a)
DSP System Toolbox                                    Version 8.4        (R2013a)
Data Acquisition Toolbox                              Version 3.3        (R2013a)
Database Toolbox                                      Version 4.1        (R2013a)
Datafeed Toolbox                                      Version 4.5        (R2013a)
Econometrics Toolbox                                  Version 2.3        (R2013a)
Embedded Coder                                        Version 6.4        (R2013a)
Filter Design HDL Coder                               Version 2.9.3      (R2013a)
Financial Instruments Toolbox                         Version 1.1        (R2013a)
Financial Toolbox                                     Version 5.1        (R2013a)
Fixed-Point Designer                                  Version 4.0        (R2013a)
Fuzzy Logic Toolbox                                   Version 2.2.17     (R2013a)
Global Optimization Toolbox                           Version 3.2.3      (R2013a)
HDL Coder                                             Version 3.2        (R2013a)
HDL Verifier                                          Version 4.2        (R2013a)
IEC Certification Kit                                 Version 3.1        (R2013a)
Image Acquisition Toolbox                             Version 4.5        (R2013a)
Image Processing Toolbox                              Version 8.2        (R2013a)
Instrument Control Toolbox                            Version 3.3        (R2013a)
MATLAB Builder EX                                     Version 2.3.1      (R2013a)
MATLAB Builder JA                                     Version 2.2.6      (R2013a)
MATLAB Builder NE                                     Version 4.1.3      (R2013a)
MATLAB Coder                                          Version 2.4        (R2013a)
MATLAB Compiler                                       Version 4.18.1     (R2013a)
MATLAB Distributed Computing Server                   Version 6.2        (R2013a)
MATLAB Report Generator                               Version 3.14       (R2013a)
Mapping Toolbox                                       Version 3.7        (R2013a)
Model Predictive Control Toolbox                      Version 4.1.2      (R2013a)
Model-Based Calibration Toolbox                       Version 4.6        (R2013a)
NCTOOLBOX Tools for read-only access to Common ...    Version 1.1.1-13-g8582810++
Neural Network Toolbox                                Version 8.0.1      (R2013a)
OPC Toolbox                                           Version 3.2        (R2013a)
Optimization Toolbox                                  Version 6.3        (R2013a)
Parallel Computing Toolbox                            Version 6.2        (R2013a)
Partial Differential Equation Toolbox                 Version 1.2        (R2013a)
Phased Array System Toolbox                           Version 2.0        (R2013a)
RF Toolbox                                            Version 2.12       (R2013a)
Real-Time Windows Target                              Version 4.2        (R2013a)
Robust Control Toolbox                                Version 4.3        (R2013a)
Signal Processing Toolbox                             Version 6.19       (R2013a)
SimBiology                                            Version 4.3        (R2013a)
SimDriveline                                          Version 2.4        (R2013a)
SimElectronics                                        Version 2.3        (R2013a)
SimEvents                                             Version 4.3        (R2013a)
SimHydraulics                                         Version 1.12       (R2013a)
SimMechanics                                          Version 4.2        (R2013a)
SimPowerSystems                                       Version 5.8        (R2013a)
SimRF                                                 Version 4.0        (R2013a)
Simscape                                              Version 3.9        (R2013a)
Simulink 3D Animation                                 Version 6.3        (R2013a)
Simulink Code Inspector                               Version 1.3        (R2013a)
Simulink Coder                                        Version 8.4        (R2013a)
Simulink Control Design                               Version 3.7        (R2013a)
Simulink Design Optimization                          Version 2.3        (R2013a)
Simulink Design Verifier                              Version 2.4        (R2013a)
Simulink PLC Coder                                    Version 1.5        (R2013a)
Simulink Report Generator                             Version 3.14       (R2013a)
Simulink Verification and Validation                  Version 3.5        (R2013a)
Spreadsheet Link EX                                   Version 3.1.7      (R2013a)
Stateflow                                             Version 8.1        (R2013a)
Statistics Toolbox                                    Version 8.2        (R2013a)
Symbolic Math Toolbox                                 Version 5.10       (R2013a)
System Identification Toolbox                         Version 8.2        (R2013a)
SystemTest                                            Version 2.6.5      (R2013a)
Trading Toolbox                                       Version 1.0        (R2013a)
Vehicle Network Toolbox                               Version 2.0        (R2013a)
Wavelet Toolbox                                       Version 4.11       (R2013a)
xPC Target                                            Version 5.4        (R2013a)
xPC Target Embedded Option                            Version 5.4        (R2013a)

**Comment by jbadag** [comment]
@hohonuuli 
-------------------------------------------------------------------------------------------------------
MATLAB Version: 8.1.0.604 (R2013a)
MATLAB License Number: 724504
Operating System: Microsoft Windows 7 Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
-------------------------------------------------------------------------------------------------------
MATLAB                                                Version 8.1        (R2013a)
Simulink                                              Version 8.1        (R2013a)
Aerospace Blockset                                    Version 3.11       (R2013a)
Aerospace Toolbox                                     Version 2.11       (R2013a)
Bioinformatics Toolbox                                Version 4.3        (R2013a)
Communications System Toolbox                         Version 5.4        (R2013a)
Computer Vision System Toolbox                        Version 5.2        (R2013a)
Control System Toolbox                                Version 9.5        (R2013a)
Curve Fitting Toolbox                                 Version 3.3.1      (R2013a)
DO Qualification Kit                                  Version 2.1        (R2013a)
DSP System Toolbox                                    Version 8.4        (R2013a)
Data Acquisition Toolbox                              Version 3.3        (R2013a)
Database Toolbox                                      Version 4.1        (R2013a)
Datafeed Toolbox                                      Version 4.5        (R2013a)
Econometrics Toolbox                                  Version 2.3        (R2013a)
Embedded Coder                                        Version 6.4        (R2013a)
Filter Design HDL Coder                               Version 2.9.3      (R2013a)
Financial Instruments Toolbox                         Version 1.1        (R2013a)
Financial Toolbox                                     Version 5.1        (R2013a)
Fixed-Point Designer                                  Version 4.0        (R2013a)
Fuzzy Logic Toolbox                                   Version 2.2.17     (R2013a)
Global Optimization Toolbox                           Version 3.2.3      (R2013a)
HDL Coder                                             Version 3.2        (R2013a)
HDL Verifier                                          Version 4.2        (R2013a)
IEC Certification Kit                                 Version 3.1        (R2013a)
Image Acquisition Toolbox                             Version 4.5        (R2013a)
Image Processing Toolbox                              Version 8.2        (R2013a)
Instrument Control Toolbox                            Version 3.3        (R2013a)
MATLAB Builder EX                                     Version 2.3.1      (R2013a)
MATLAB Builder JA                                     Version 2.2.6      (R2013a)
MATLAB Builder NE                                     Version 4.1.3      (R2013a)
MATLAB Coder                                          Version 2.4        (R2013a)
MATLAB Compiler                                       Version 4.18.1     (R2013a)
MATLAB Distributed Computing Server                   Version 6.2        (R2013a)
MATLAB Report Generator                               Version 3.14       (R2013a)
Mapping Toolbox                                       Version 3.7        (R2013a)
Model Predictive Control Toolbox                      Version 4.1.2      (R2013a)
Model-Based Calibration Toolbox                       Version 4.6        (R2013a)
NCTOOLBOX Tools for read-only access to Common ...    Version 1.1.1-13-g8582810++
Neural Network Toolbox                                Version 8.0.1      (R2013a)
OPC Toolbox                                           Version 3.2        (R2013a)
Optimization Toolbox                                  Version 6.3        (R2013a)
Parallel Computing Toolbox                            Version 6.2        (R2013a)
Partial Differential Equation Toolbox                 Version 1.2        (R2013a)
Phased Array System Toolbox                           Version 2.0        (R2013a)
RF Toolbox                                            Version 2.12       (R2013a)
Real-Time Windows Target                              Version 4.2        (R2013a)
Robust Control Toolbox                                Version 4.3        (R2013a)
Signal Processing Toolbox                             Version 6.19       (R2013a)
SimBiology                                            Version 4.3        (R2013a)
SimDriveline                                          Version 2.4        (R2013a)
SimElectronics                                        Version 2.3        (R2013a)
SimEvents                                             Version 4.3        (R2013a)
SimHydraulics                                         Version 1.12       (R2013a)
SimMechanics                                          Version 4.2        (R2013a)
SimPowerSystems                                       Version 5.8        (R2013a)
SimRF                                                 Version 4.0        (R2013a)
Simscape                                              Version 3.9        (R2013a)
Simulink 3D Animation                                 Version 6.3        (R2013a)
Simulink Code Inspector                               Version 1.3        (R2013a)
Simulink Coder                                        Version 8.4        (R2013a)
Simulink Control Design                               Version 3.7        (R2013a)
Simulink Design Optimization                          Version 2.3        (R2013a)
Simulink Design Verifier                              Version 2.4        (R2013a)
Simulink PLC Coder                                    Version 1.5        (R2013a)
Simulink Report Generator                             Version 3.14       (R2013a)
Simulink Verification and Validation                  Version 3.5        (R2013a)
Spreadsheet Link EX                                   Version 3.1.7      (R2013a)
Stateflow                                             Version 8.1        (R2013a)
Statistics Toolbox                                    Version 8.2        (R2013a)
Symbolic Math Toolbox                                 Version 5.10       (R2013a)
System Identification Toolbox                         Version 8.2        (R2013a)
SystemTest                                            Version 2.6.5      (R2013a)
Trading Toolbox                                       Version 1.0        (R2013a)
Vehicle Network Toolbox                               Version 2.0        (R2013a)
Wavelet Toolbox                                       Version 4.11       (R2013a)
xPC Target                                            Version 5.4        (R2013a)
xPC Target Embedded Option                            Version 5.4        (R2013a)

**Comment by jbadag** [comment]
@hohonuuli do you need more information about the problem?

Thank you for your attention!

**Comment by CristianParraM** [comment]
I have a similar problem, the code works fine if executed in matlab, but I think an .exe throws the error:
![sin titulo](https://cloud.githubusercontent.com/assets/16765782/12402033/12b7d7aa-be09-11e5-92b9-2265718f32d5.png)
