### ISSUE TITLE
Give geosubset the ability to access the "top" or "bottom" layer

### ISSUE THREAD

**Issue by rsignell-usgs** [nctoolbox/nctoolbox#55]
@acrosby , do you think it would be hard to allow users to specify "top" or "bottom" layer via the geosubset `z_index`?   I'm wondering whether, for example, we could specify `s.z_index='top'` or `s.z_index='bottom'` and have geosubset figure out which layer to extract (`1` or `end`).

This would help folks who are just trying to look at surface temperature not have to specify 1 if it's NCOM, but 30 if it's ROMS, etc...

**Comment by rsignell-usgs** [comment]
@acrosby, did you get far enough to scope the effort that would be required to add this enhancement?

**Comment by acrosby** [comment]
I think I can do it. I'll give my fix a try after work before I head home today. (Don't have matlab at home.)

**Comment by rsignell-usgs** [comment]
I fiddled a bit yesterday and got this going:
https://github.com/rsignell-usgs/nctoolbox/blob/v1.0.x/cdm/ncgeovariable.m#L750-L764

**Comment by acrosby** [comment]
@rsignell-usgs seems like that should work as you expect. I was looking at adding some functionality into the `indexing.m`  as well. Do you think that the names should be configured to work with atmospheric datasets as well? 

I was thinking that sometimes `surface` == `bottom`, and sometimes `top` == `surface` depending on the data. Maybe include all 3 as acceptable?

**Comment by rsignell-usgs** [comment]
@acrosby, great point.   It should be `top` and `bottom`, and that's all.  No `surface`.   I called the routine `top_bot`, but then put `surface` into the logic.  Stupid.  I'll fix.

**Comment by acrosby** [comment]
Great! If it works like you expect submit a pull request and merge it in.

**Comment by rsignell-usgs** [comment]
Fixed in https://github.com/nctoolbox/nctoolbox/pull/58
