### ISSUE TITLE
Strange setup_nctoolbox error

### ISSUE THREAD

**Issue by rsignell-usgs** [nctoolbox/nctoolbox#59]
I was helping a user try to test this version of nctoolbox:
https://github.com/rsignell-usgs/nctoolbox/archive/v1.0.x.zip
 and when they type `setup_nctoolbox` they get this error:
```
>> setup_nctoolbox
??? Error using ==> setup_nctoolbox at 16
Failed to setup the Java classpath
 
>> setup_nctoolbox_java
??? Undefined variable "org" or class "org.apache.log4j.Logger.getRootLogger".

Error in ==> setup_nctoolbox_java at 5
root = org.apache.log4j.Logger.getRootLogger();
```
They are using an old Matlab 2009a box, running linux 64, but the strange thing is that they have no problem running `setup_nctoolbox` on this version:
https://github.com/nctoolbox/nctoolbox/archive/1.0.0.zip

**Comment by daf** [comment]
I'm not going to be much help for the actual problem at hand, but do we know when the 1.0.0 zip was made, aka which git commit?  Doesn't appear to be a related tag.  I was going to compare that and the 1.0.x tags/branches and try to see if it was obvious based on that.  (the tag can still be added if anyone knows)

**Comment by rsignell-usgs** [comment]
This is the commit.  https://github.com/rsignell-usgs/nctoolbox/commit/a34d3ab92b2f1083bfc9ce52bd449e84fca86c8b
Now that you mention it, perhaps it's the java files changing?

**Comment by hohonuuli** [comment]
The upshot is that the 1.0.x does not contain a `log4j.jar`. The current version of Matlab (R2014b) has that jar on the classpath already, so it's not needed. Older versions of Matlab apparently do not. So for 2009a you'll need to drop a log4j.jar file into the `nctoolbox\java` directory. We can add a conditional workaround in `setup_nctoolbox_java.m` if needed. You can download the most recent version of log4j at [http://search.maven.org/remotecontent?filepath=log4j/log4j/1.2.17/log4j-1.2.17.jar](http://search.maven.org/remotecontent?filepath=log4j/log4j/1.2.17/log4j-1.2.17.jar)

The reason 1.0.0 works is that it's java directory contains log4j.jar

**Comment by hohonuuli** [comment]
__TODO:__ Add a conditional to `setup_nctoolbox_java.m` so that log4j get's added to Matlab's java classpath if it's not found.

**Comment by hohonuuli** [comment]
Just a not that the location of log4j in Matlab R2014b on Mac is /Applications/MATLAB_R2014b.app/java/jarext/log4j.jar

**Comment by rsignell-usgs** [comment]
Yep, adding that jar file worked for our Matlab 2009 user.  Yea!

**Comment by daf** [comment]
@rsignell-usgs, I meant the commit that corresponds to 1.0.0.zip.  1.0.x is tagged properly.

**Comment by chstefanakos** [comment]
Hi, I just downloaded the latest version of nctoolbox from github. I am using MATLAB R2021b. When I tried "setup_nctoolbox", I got the following ERROR message : "Failed to setup the Java classpath". 
Following your post, I checked nctoolbox and I saw that in C:\Program Files\MATLAB\nctoolbox-master\java\ it contains the file "log4j-1.2.17.jar", and my MATLAB distribution contain in C:\Program Files\MATLAB\R2021b\java\jarext 3 files : 
log4j-1.2-api-2.17.0.jar
log4j-api-2.17.0.jar
log4j-core-2.17.0.jar
I tried 2 actions:
1/ Delete the log4j-1.2.17.jar from nctoolbox-master\java\
2/ Copy the 3 jar files from R2021b path to nctoolbox path
In both cases, I got the same error message :(
Any suggestions how to fix this problem ?

**Comment by hohonuuli** [comment]
@chstefanakos Can you include the full error message?

**Comment by chstefanakos** [comment]
Error using setup_nctoolbox (line 17)
Failed to setup the Java classpath

**Comment by hohonuuli** [comment]
Can you run `setup_nctoolbox_java` and post it's message.

**Comment by chstefanakos** [comment]
No constructor 'org.apache.log4j.ConsoleAppender' with matching signature found.

Error in setup_nctoolbox_java (line 6)
root.addAppender(org.apache.log4j.ConsoleAppender(org.apache.log4j.PatternLayout('%d{ISO8601} [%t] %-5p %c %x - %m%n')));

**Comment by hohonuuli** [comment]
The quickest fix for you is probably just to comment out line 6 in `setup_nctoolbox_java.m`. Commenting it out won't break anything.

**Comment by chstefanakos** [comment]
Thanks. It works for the moment...

**Comment by hohonuuli** [comment]
Thanks for the huge vote of confidence ...

**Comment by nehupp** [comment]
I am still getting the error after using this also 
setup_nctoolbox_java.m

**Comment by gunna1111** [comment]
> No constructor 'org.apache.log4j.ConsoleAppender' with matching signature found.
> 
> Error in setup_nctoolbox_java (line 6) root.addAppender(org.apache.log4j.ConsoleAppender(org.apache.log4j.PatternLayout('%d{ISO8601} [%t] %-5p %c %x - %m%n')));

same question

**Comment by gunna1111** [comment]
Thanks

**Comment by hohonuuli** [comment]
@nehupp @gunna1111 Did you apply the fix listed earlier in the issue (i.e. comment out line 6)
