### ISSUE TITLE
Permissions issue with a cache path

### ISSUE THREAD

**Issue by grapesh** [nctoolbox/nctoolbox#74]
Hi

I wonder if there's a way to configure cache paths for users with no Administrator privileges (Windows).

All the supplied demo tests pass, but when I try to open an actual GRIB2 file, here's what happens:

nc=ncgeodataset('gfs.t00z.pgrb2.0p25.f000');
2015-04-22 09:14:58,507 [main] ERROR cacheLogger  - DiskCache2 failed to create directory C:/Users/Administrator/.unidata/cache/

Thanks!

**Comment by rsignell-usgs** [comment]
@grapesh, I thought that in the 4.3.15 version of NetCDF-Java being used by NCTOOLBOX, the cached grib index files get written in the local directory.   But this message
http://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg12110.html
indicates the java commands one could use to __specify__ the cache location:
```java
   // Inform NJ where the cache is and to always use it.
     DiskCache.setRootDirectory  (cachepath);
     DiskCache.setCachePolicy    (true);

   // The following is necessary as of NJ 4.3.15 in order to prevent GRIB
   // temp files from cluttering up same directory as source GRIB files.
     DiskCache2 dc2 = new DiskCache2 (cachepath, false, 30, 30);
     dc2.setAlwaysUseCache (true);
     GribCollection.setDiskCache2 (dc2);
```
But we might need @hohonuuli to tell us how to do the same using Matlab.

**Comment by hohonuuli** [comment]
That looks pretty straight forward. I'll throw together a matlab function  to wrap this tomorrow.

**Comment by grapesh** [comment]
@hohonuuli thanks, this would be great!

**Comment by hohonuuli** [comment]
... and I forgot to do this, didn't I? I'll deal with it this morning. Cheers

**Comment by hohonuuli** [comment]
I added a new file named [setnccache.m](https://github.com/nctoolbox/nctoolbox/blob/master/cdm/utilities/misc/setnccache.m) to the _master_ branch. It _seems_ to work, but I need a grib to test against. Can someone either run a quick test to verify it works or point me at a grib? Once that's done we can just tag a new release (1.1.2?) on the master branch.

Cheers

**Comment by grapesh** [comment]
Brian, here is an example of GRIB2 file:
http://nomads.ncep.noaa.gov/pub/data/nccf/com/estofs/prod/estofs.20150427/estofs.atl.t00z.conus.f000.grib2
I checked a new function and it <i>seems</i> to work for me as well - I could set a new cache to my account space instead of Admin's - but I haven't done any more in-depth testing.

**Comment by hohonuuli** [comment]
Tested with:

```matlab
setnccache('/Users/brian/Downloads/testcache')
nc = cfdataset('/Users/brian/Downloads/estofs.atl.t00z.conus.f000.grib2')
```

The _testcache_ directory was created and the following index files were created in `/Users/brian/Downloads/testcache`:
- Users-brian-Downloads-estofs.atl.t00z.conus.f000.grib2.gbx9
- Users-brian-Downloads-estofs.atl.t00z.conus.f000.grib2.ncx

So it appears all is working as expected. Closing issue.

**Comment by hohonuuli** [comment]
Also, just a note that the cached files must be manually deleted. You make them, you manage them.
