### ISSUE TITLE
[question] java.lang.OutOfMemoryError: Java heap space 

### ISSUE THREAD

**Issue by youngshin-kim** [nctoolbox/nctoolbox#78]
Hi ! 
I'm trying to read ETOPO1 data. But I couldn't read that data. please help me. 
my OS is win 7 64bit, MATLAB version= 2014b, Java version is Java 1.7.0_11-b21 (64bit)

here is my matlab code 

  setup_nctoolbox
  Fn='ETOPO1_Bed_g_gdal.grd';
  nc= ncgeodataset(Fn);
  x_rng=nc.data('x_range');
  y_rng=nc.data('y_range');
  z_rng=nc.data('z_range');
  SP=nc.data('spacing');
  Di=nc.data('dimension');
  Z=nc.data('z');

and error message is follows;

Error using ncdataset/readdata (line 460)
Java exception occurred:
java.lang.OutOfMemoryError: Java heap space

	at ucar.nc2.iosp.IospHelper.makePrimitiveArray(IospHelper.java:780)

	at ucar.nc2.iosp.IospHelper.readDataFill(IospHelper.java:77)

	at ucar.nc2.iosp.netcdf3.N3raf.readData(N3raf.java:63)

	at ucar.nc2.iosp.netcdf3.N3iosp.readData(N3iosp.java:453)

	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1941)

	at ucar.nc2.Variable.reallyRead(Variable.java:859)

	at ucar.nc2.Variable._read(Variable.java:831)

	at ucar.nc2.Variable.read(Variable.java:709)

	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:518)

	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:502)

	at ucar.nc2.Variable.read(Variable.java:709)

Error in ncdataset/data (line 159)
                    d = obj.readdata(variable);

Error in ncgeodataset/subsref (line 386)
                            B = builtin('subsref',obj,g);

**Comment by rsignell-usgs** [comment]
You can probably read the data if you don't try to read the whole world, which is what
```
Z=nc.data('z')
```
is trying to do.

Instead extract just what you need using the geosubset method:
```
url='http://www.ngdc.noaa.gov/thredds/dodsC/relief/ETOPO1/thredds/ETOPO1_Bed_g_gmt4.nc'
nc = ncgeodataset(url);
nc.variables
zvar = nc.geovariable('z');
s.lat=[40.5 42.5];
s.lon=[-71.5 -69];
z = zvar.geosubset(s);
pcolor(z.grid.lon,z.grid.lat,double(z.data));shading flat
```
loads the data for the Cape Cod region:
![6-16-2015 11-49-16 am](https://cloud.githubusercontent.com/assets/1872600/8187447/c06b1240-141d-11e5-8447-ce00a5ca0545.png)

You can read your local file using the same code.  




whole world?

**Comment by hohonuuli** [comment]
You can also try increasing your Java heap size. See http://blogs.mathworks.com/community/2010/04/26/controlling-the-java-heap-size/

**Comment by youngshin-kim** [comment]
Thank you very much !!! 
I can read data using the geosubset method as rsignell-usgs's comment, thank you for sample code. It  is great help for me.
I also increased my java heap size, It is also a great tip.
Thank you again.
