### ISSUE TITLE
setup_nctoolbox fails for Octave

### ISSUE THREAD

**Issue by garydoctors** [nctoolbox/nctoolbox#81]
To prevent the error below, I changed the name=java.lang line in addjars.m to name = javaObject("java.lang.String", d(i).name);  I then got a bit futher, but I have the error 5: root = org.apache.log4j.Logger.getRootLogger();
debug>
error: 'org' undefined near line 5 column 8
in the file setup_nctoolbox_java.m.
******************************
I've installed the nctoolbox and I tried to set it up in GNU Octave.  I had an error, where an exception was thrown in setup_nctoolbox.m and I tried to debug it.  
>> setup_nctoolbox
error: 'MException' undefined near line 15 column 10
error: called from:
error:   C:\Users\Gary Doctors\Documents\GitHub\CUER_RaceStrategy\nctoolbox\setup_nctoolbox.m at line 15, column 8

Something is going wrong with java.m.  
>> setup_nctoolbox
stopped in C:\Users\Gary Doctors\Documents\GitHub\CUER_RaceStrategy\nctoolbox\java\addjars.m at line 7
7:     name = java.lang.String(d(i).name);
debug>
error: invalid call to script C:\Octave\Octave-3.8.2\share\octave\packages\java-1.2.9\java.m
error: called from:
error:   C:\Users\Gary Doctors\Documents\GitHub\CUER_RaceStrategy\nctoolbox\java\addjars.m at line 7, column 10
error:   C:\Users\Gary Doctors\Documents\GitHub\CUER_RaceStrategy\nctoolbox\java\setup_nctoolbox_java.m at line 2, colum
n 1
error: called from:
error:   C:\Users\Gary Doctors\Documents\GitHub\CUER_RaceStrategy\nctoolbox\setup_nctoolbox.m at line 15, column 8
>> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
        java *|   1.2.9 | C:\Octave\Octave-3.8.2\share\octave\packages\java-1.2.9

Please can you help me with this?

**Comment by rsignell-usgs** [comment]
We haven't done any testing of NCTOOLBOX with Octave.
I would imagine there would be some issues, because according to  this page:
http://wiki.octave.org/Java_package
there are differences between the way that Matlab and Octave import java..

Please let us know if you have success!

**Comment by hohonuuli** [comment]
I don't think _nctoolbox_ will ever work in Octave. To start, the specific error you're getting is: `error: 'MException' undefined near line 15 column 10`. Octave does not support all of Matlab's error handling; there's a bug report for this at [https://savannah.gnu.org/bugs/?40828](https://savannah.gnu.org/bugs/?40828).

Also, _nctoolbox_ uses [Matlab's newer object-oriented syntax](https://www.mathworks.com/help/matlab/object-oriented-programming.html) which is not supported by Octave.
