### ISSUE TITLE
Combine u and v wind components in matlab

### ISSUE THREAD

**Issue by joeyjanssen** [nctoolbox/nctoolbox#88]
I am trying to combine the u and v wind components from a GRIB2 file and eventually plot this combined vector. Link to GRIB file:[https://dl.dropboxusercontent.com/u/23413968/GRIB/gfsanl_4_20140308_0000_006.grb2](url)
I hope someone can help me with writing the code in order to make this happen, i am not very experienced working with matlab but really need this to work for my thesis. 

Thanks,

Joey

**Comment by joeyjanssen** [comment]
https://dl.dropboxusercontent.com/u/23413968/GRIB/gfsanl_4_20140308_0000_006.grb2

**Comment by hohonuuli** [comment]
Theoretically:

```matlab
nc = ncdataset('gfsanl_4_20140308_0000_006.grb2');
u = nc.data('u-component_of_wind_maximum_wind');
v = nc.data('v-component_of_wind_maximum_wind');
```

But when I run that I get

```
Error using ncdataset/readdata (line 467)
Java exception occurred:
java.io.FileNotFoundException: data file not found = /Users/brian/Documents/MATLAB/gfsanl_4_20140308_0000_006.grb2
	at ucar.nc2.grib.GribCollection.getDataRaf(GribCollection.java:387)
	at ucar.nc2.grib.grib2.Grib2Iosp$DataReader.read(Grib2Iosp.java:973)
	at ucar.nc2.grib.grib2.Grib2Iosp.readDataFromCollection(Grib2Iosp.java:912)
	at ucar.nc2.grib.grib2.Grib2Iosp.readData(Grib2Iosp.java:720)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1957)
	at ucar.nc2.Variable.reallyRead(Variable.java:841)
	at ucar.nc2.Variable._read(Variable.java:813)
	at ucar.nc2.Variable.read(Variable.java:691)
	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:519)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:503)
	at ucar.nc2.Variable.read(Variable.java:691)

Error in ncdataset/data (line 165)
                    d = obj.readdata(variable);
```

Which is a bug in the GRIB library. Unfortunately, I'm kind of stuck and can't address this issue. I think it's fixed in more recent versions of the Java GRIB libraries. However, I can't upgrade nctoolbox to more current versions of netcdf/grib. NetCDF < 4.3 and Matlab both use [commons-http](https://hc.apache.org/httpclient-3.x/) java library; so they play fine together. NetCDF > 4.3 uses [http-client](https://hc.apache.org/) which can't be run in the same Java VM (i.e Matlab) as commons-http.

**Comment by joeyjanssen** [comment]
Thanks for the effort in trying to solve the problem, i appreciate your help very much. When i define the nc.geodataset i fill in the whole path to the grib file:

`nc=ncgeodataset('C:\dev\joey\GRIB\GRIB files\gfsanl_4_20140308_0000_006.grb2')`

This works fine for me. So i have u and v defined but my biggest struggle is how to combine these to into a vector and plot this. Could you maybe provide the code which should work for me, if this is possible for you without trying yourself. I also made a javaclasspath.txt file in the preference folder of madlab to solve tha java problem which i figured out thanks to you. I hope you are still able to help me with this problem.

kind regards,

Joey

**Comment by rsignell-usgs** [comment]
@joeyjanssen , it sounds like you have solved your nctoolbox issue.   For issues with plotting vectors, I suggest you check out the Mathworks help pages, like this one: http://www.mathworks.com/help/matlab/ref/quiver.html

And if you have problems, ask questions on stackoverflow:, like this one: http://stackoverflow.com/questions/1962332/how-to-draw-vectors-physical-2d-3d-vectors-in-matlab

**Comment by joeyjanssen** [comment]
Yes the nctoolbox issue is fixed, in the sense that the toolbox itself works. However the problem of combining the u and v components into a speed and direction vector is still unsolved. This is were i would like receive some help.

**Comment by rsignell-usgs** [comment]
@joeyjanssen, would you agree this is not a nctoolbox issue, but a general Matlab usage issue?

Did you try the Mathworks and StackOverflow links I provided above?

**Comment by joeyjanssen** [comment]
Yes i agree and yes i looked at them but wasn't able to figure out how to apply them to my problem. The reason why i asked the question on this forum is because this combining problem specifically occurs while using grib files so I imagened someone here did it before and could help me with this problem. I hope you are still able to help me, thanks

**Comment by rsignell-usgs** [comment]
I don't believe this has anything to do with grib files -- you have u and v components as matlab variables, correct?   I suggest that if you are still struggling after reading the Matlab and SO links, you either ask on StackOverflow or contact Matlab support -- that's partly why you pay for a Matlab license!
