### ISSUE TITLE
Reading grb2 file in matlab

### ISSUE THREAD

**Issue by machaielder** [nctoolbox/nctoolbox#97]
I am trying to read grb2 file using nctoolbox in matlab but I am getting the following error 
```
Error using ucar.nc2.dataset.VariableDS/read
Java exception occurred:
java.io.FileNotFoundException: data file not found =
/home/helder/multi_reanal.glo_30m.dp.200703.grb2
	at ucar.nc2.grib.GribCollection.getDataRaf(GribCollection.java:387)
	at ucar.nc2.grib.grib2.Grib2Iosp$DataReader.read(Grib2Iosp.java:973)
	at ucar.nc2.grib.grib2.Grib2Iosp.readDataFromCollection(Grib2Iosp.java:912)
	at ucar.nc2.grib.grib2.Grib2Iosp.readData(Grib2Iosp.java:720)
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1957)
	at ucar.nc2.Variable.reallyRead(Variable.java:879)
	at ucar.nc2.Variable._read(Variable.java:865)
	at ucar.nc2.Variable.read(Variable.java:677)
	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:553)
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:533)
	at ucar.nc2.Variable.read(Variable.java:677)
	at ucar.nc2.Variable.read(Variable.java:651)

Error in ncdataset/readdata (line 494)
                array = v.read(ranges);

Error in ncdataset/data (line 171)
                    d = obj.readdata(variable, first, last, stride);

Error in ncgeodataset/subsref (line 630)
                            B = builtin('subsref',obj,g);

the commands are here:
% create ncgeodataset object
nc=ncgeodataset('multi_reanal.glo_30m.dp.200703.grb2');

% list variables
nc.variables

% create geovariable object
dirvar=nc.geovariable('Primary_wave_direction_surface');

% get data at 1st time step
dir=dirvar.data(1,:,:);

% get grid at 1st time step
g=dirvar.grid_interop(1,:,:);

% plot
pcolorjw(g.lon,g.lat,dir);
title(datestr(g.time))
```
my java version:
Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode

Can anyone help me..

**Comment by rsignell-usgs** [comment]
What version of nctoolbox are you using?

Can you try the 1.1.1 version and see if it works?
https://github.com/nctoolbox/nctoolbox/archive/1.1.1.zip

**Comment by machaielder** [comment]
Hi Rsignell-usgs
Thank You!
I tried 1.1.1 version and doesnt work!
Your suggestions are welcome!

**Comment by rsignell-usgs** [comment]
Can you provide the file on dropbox or google drive?

**Comment by machaielder** [comment]
I have just attachment sent shared with you

**Comment by rsignell-usgs** [comment]
You can't email to github with an attachment, but I googled and found the file here:
ftp://polar.ncep.noaa.gov/pub/history/waves/multi_1/200703/gribs/multi_1.glo_30m.dp.200703.grb2
after downloading, it read with my Matlab 2015b and NCTOOLBOX 1.1.1 just fine:

![2017-02-21_14-16-05](https://cloud.githubusercontent.com/assets/1872600/23180750/7a319ce6-f840-11e6-9129-1dd6a917b1d1.png)

What version of Matlab are you using?

**Comment by rsignell-usgs** [comment]
```
url='C:/Users/rsignell/Downloads/multi_1.glo_30m.dp.200703.grb2'
nc = ncgeodataset(url)
dirvar=nc.geovariable('Primary_wave_direction_degree_true_surface');
dir=dirvar.data(1,:,:);
dir = squeeze(dir);
dir(1:10,1:10)

ans =

       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN       NaN
    6.0600    3.5300    1.4000  359.4100  357.5200  355.6600  353.9300  352.1800  350.4400  348.7600
   11.2400    9.0100    7.1700    5.5400    3.9700    5.8300    4.0700    2.3900    0.8100  359.3400
   19.5000   17.9300   16.4300   14.9700   13.4900   12.0200   10.5500    9.1100    7.7000    6.3000
   26.3400   25.2600   24.1500   23.0000   21.8500   20.6900   19.5800   18.5300   17.5100   16.5500
   31.0200   30.2000   29.5500   31.2900   31.0800   31.0500   31.1200   31.3700   44.2500   45.6700
   51.4600   51.6300   52.2300   53.2000   54.4100   55.7900   57.2500   58.7400   60.0200   61.0500
   65.6100   66.4200   67.4800   68.6800   69.9300   71.1100   72.1600   73.0000   73.6100   73.8900
   73.3800   73.9400   74.5900   75.3000   76.0600   76.7800   77.3500   77.7500   77.8000   77.6600
   73.4200   74.2500   75.0500   75.7500   76.2300   76.5600   76.6700   76.4900   76.1300   75.4100
```

**Comment by machaielder** [comment]
My matlab version is (R2012a). I still get the same error. Did receive the file file in google drive?
can You please explain how to share using URL in case You did not receive.

Thank You!

**Comment by rsignell-usgs** [comment]
So if you download this file: ftp://polar.ncep.noaa.gov/pub/history/waves/multi_1/200703/gribs/multi_1.glo_30m.dp.200703.grb
and repeat my commands above it doesn't work?

**Comment by machaielder** [comment]
your file works , what's wrong with mine? Thank You!
Are familiar with this dataset? My aim is to analyze waves variability...
 

clear all; close all;
url='multi_1.glo_30m.dp.200703.grb2'
nc = ncgeodataset(url)
dirvar=nc.geovariable('Primary_wave_direction_degree_true_surface');
lat=nc.geovariable('lat');
lat=lat.data(:)
lon=nc.geovariable('lon');
lon=lon.data(:);
time=nc.geovariable('time');
time=time.data(:);


dir=dirvar.data(1,:,:);
dir = squeeze(dir);
dir(1:10,1:10)

**Comment by machaielder** [comment]
your file works , what's wrong with mine? Thank You!
Are familiar with this dataset? My aim is to analyze waves variability...
 

clear all; close all;
url='multi_1.glo_30m.dp.200703.grb2'
nc = ncgeodataset(url)
dirvar=nc.geovariable('Primary_wave_direction_degree_true_surface');
lat=nc.geovariable('lat');
lat=lat.data(:)
lon=nc.geovariable('lon');
lon=lon.data(:);
time=nc.geovariable('time');
time=time.data(:);


dir=dirvar.data(1,:,:);
dir = squeeze(dir);
dir(1:10,1:10)

**Comment by rsignell-usgs** [comment]
I don't know what's wrong with yours.  Sorry.  How about getting them from the source I provided?

**Comment by machaielder** [comment]
Yes I decided to get them from the source you provided. My aim is to get time series ..
I got error when a changed dir=dirvar.data(a,:,:) to dir=dirvar.data(:,:,:) and I dont see the reason for the error. Any idea?

**Comment by rsignell-usgs** [comment]
The error is `java.lang.OutOfMemoryError: Java heap space`

This means you ran out of memory for Java because you tried to load a big chunk of data all at once: `dir=dirvar.data(:,:,:);`.

So you can either:
1) increase the amount of memory given to Java in Matlab
https://www.mathworks.com/help/matlab/matlab_external/java-heap-memory-preferences.html
or for older Matlab versions, see:
https://www.mathworks.com/matlabcentral/answers/92813-how-do-i-increase-the-heap-space-for-the-java-vm-in-matlab-6-0-r12-and-later-versions

or 

2) loop through time instead of trying to read all at once.   This is normally what I do with large files.  
e.g.    for i=1:n,
              dir=dirvar.data(i,:,:); 
              process....

**Comment by machaielder** [comment]
The loop worked, thank You!

clear all; close all;
url='multi_1.glo_30m.dp.201303.grb2'
nc = ncgeodataset(url)
dirvar=nc.geovariable('Primary_wave_direction_degree_true_surface');
lat=nc.geovariable('lat');
lat=lat.data(:)
lon=nc.geovariable('lon');

lon=lon.data(:);
time=nc.geovariable('time');
time=time.data(:);
i= find(lat>=-27 & lat <= -12 );
     ii= find(lon>= 32 & lon <= 40);
 for n=1:length(time),
dir(n,:,:)=dirvar.data(n,i,ii);
 end

**Comment by rsignell-usgs** [comment]
Awesome!  Do you want to close this ticket then?
