### ISSUE TITLE
Reading Modis HDF file 

### ISSUE THREAD

**Issue by aerosol1234** [nctoolbox/nctoolbox#98]
Hi guys, 

I am trying to read the Modis HDF file for the first time in Matlab using nctoolbox. I have pasted the code below.  I am seeing an error when I try to extract a variable of my interest (see zvar in the code below). the error message is 

"The class ucar.nc2.NetcdfFile has no property or method named 'escapeName'.

Error in ncdataset/findvariable (line 454)
                v = obj.netcdf.findVariable(ucar.nc2.NetcdfFile.escapeName(variable))"

%%%%% (CODE)
addpath('c:\Users\asi\Documents\AQ_PROCESSING_SYSTEM\gen_utility_code\ashish_additions\nctoolbox-master')
setup_nctoolbox 

ti = ncgeodataset('C:\Users\asi\Documents\AQ_PROCESSING_SYSTEM\raw_data\satelite_PM\2013_MOD04_3K_Collection_6\MOD04_3K.A2013001.0325.006.2015064204145.hdf');
ti.variables
zvar = ti.geovariable('Corrected_Optical_Depth_Land');

**Comment by rsignell-usgs** [comment]
I'm pretty sure that NCTOOLBOX can't read Modis HDF. 

You should be able to read it using the native HDF reader, though.

https://www.mathworks.com/matlabcentral/answers/161942-how-to-read-or-extract-modis-hdf-aerosol-data
